whole_genome_bincnt_file: 'output/histone_data/alltogether_notnormed_logtrans.txt.gz'
chann_stats_file: 'output/tensor_data/chann_stats.csv'
window_width: 100
number_of_windows: 20
batch_size: 1024
num_classes: 5
prob_conf_cutoff: 0.5
cpu_threads: 6
data_augment: False
# model state (parameters) from the training module.
model_state_dict: 'output/model/best-mAP-model.pt'
output_bed: 'wg_preds.bed'
tpms_file: 'output/tpms_data/final_tpms.bed'
tpm_bps_added: 2500  # default from Kim et al.






